name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build
        run: bash ./SkejbyDiceJava/gradlew
